CREATE TABLE Users (
    UserId INT IDENTITY(1,1) NOT NULL UNIQUE,
    Fullname NVARCHAR(255),
    Email NVARCHAR(255) UNIQUE,
    Password NVARCHAR(255),
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (UserId)
);

CREATE TABLE Questions (
    QuestionID INT IDENTITY(1,1) NOT NULL UNIQUE,
    QuestionText NVARCHAR(MAX) NOT NULL,
    Option1 NVARCHAR(50) NOT NULL,
    Option2 NVARCHAR(50) NOT NULL,
    Option3 NVARCHAR(50) NOT NULL,
    Option4 NVARCHAR(50) NOT NULL,
    CorrectOption NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (QuestionID)
);

CREATE TABLE Courses (
    CourseID INT IDENTITY(1,1) NOT NULL UNIQUE,
    CourseName NVARCHAR(255) NOT NULL,
    PRIMARY KEY (CourseID)
);

CREATE TABLE Certificates (
    CertificateId INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    CourseName NVARCHAR(255) NOT NULL,
    Score DECIMAL(5,2) NOT NULL,
    CertificatePath NVARCHAR(500) NOT NULL,
    IssueDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE CASCADE
);


CREATE TABLE UserSubmissions (
    SubmissionID INT IDENTITY(1,1) PRIMARY KEY, 
    UserID INT NOT NULL, 
    CourseID INT NOT NULL, 
    QuestionID INT NOT NULL, 
    SelectedOption NVARCHAR(10) NOT NULL, 
    SubmissionTime DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_User FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    CONSTRAINT FK_Course FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE,
    CONSTRAINT FK_Question FOREIGN KEY (QuestionID) REFERENCES Questions(QuestionID) ON DELETE CASCADE
);